In [9]:
import json
import datetime
from IPython.display import display, HTML
import pandas as pd
from pandas.io.json import json_normalize

file = open('./Backup_2018-08-08_20-16-53.pctb','r')
data = json.loads(file.read())

# Date Utils

In [47]:
date = datetime.datetime.fromtimestamp(20)
# %d is the day number
# %m is the month number
# %b is the month abbreviation
# %y is the year last two digits
# %Y is the all year

def total_time(timestamp):
    hours = timestamp / 60 / 60
    minutes = int((hours % 1) * 60)
    hours = int(hours//1)
    return "{}:{}".format(hours,minutes)
     

def print_datetime(timestamp):
    return datetime.datetime.fromtimestamp(timestamp).strftime("%Y/%m/%d - %H:%M")

def print_hour(timestamp):
    date = datetime.datetime.fromtimestamp(timestamp)
    return date.strftime("%H:%M")

def print_minutes(timestamp):
    return datetime.datetime.fromtimestamp(timestamp).strftime("%M")

# Pomodoros

In [127]:
df_pomodoros = json_normalize(data['pomodoros'])

def format_pomodoros(df_original):
    df = df_original.copy()
    df['_t'] = df['_t'].apply(lambda x: print_hour(x))
    df['_d'] = df_pomodoros['_d'].apply(lambda x: print_minutes(x))
    df.rename(columns={'_t':'Time', '_d':'Duration', '_dt': 'Date', '_id': 'Id'}, inplace=True)
    df = df.drop('_msc', 1)
    df = df.drop('_m', 1)
    df = df.drop('_ty', 1)
    df = df.drop('_r', 1)
    df = df.drop('_f', 1)
    return df
format_pomodoros(df_pomodoros)

     Duration        Date    Id   Time
0          25  2017/06/30     1  16:42
1          25  2017/06/30     2  17:56
2          25  2017/06/30     3  18:23
3          25  2017/06/30     4  19:31
4          25  2017/06/30     5  20:07
5          25  2017/06/30     6  21:18
6          25  2017/07/04     7  11:29
7          25  2017/07/04     8  12:00
8          25  2017/07/04     9  12:49
9          25  2017/07/04    10  13:27
10         25  2017/07/04    11  21:57
11         25  2017/07/04    12  23:18
12         25  2017/07/05    13  15:18
13         25  2017/07/05    14  16:51
14         25  2017/07/05    15  18:59
15         25  2017/07/05    16  19:33
16         25  2017/07/05    17  21:54
17         25  2017/07/05    18  22:20
18         25  2017/07/06    19  09:53
19         25  2017/07/06    20  10:52
20         25  2017/07/06    21  11:43
21         25  2017/07/06    22  12:41
22         25  2017/07/06    23  13:24
23         25  2017/07/06    24  14:09
24         25  2017/07/06    25  14:47
25         25  2017/07/06    26  15:30
26         25  2017/07/06    27  17:49
27         25  2017/07/06    28  20:02
28         25  2017/07/06    29  20:35
29         25  2017/07/07    30  17:45
30         25  2017/07/07    31  18:15
31         25  2017/07/07    32  20:06
32         25  2017/07/07    33  20:43
33         25  2017/07/08    34  13:10
34         25  2017/07/08    35  13:58
35         25  2017/07/08    36  15:41
36         25  2017/07/08    37  17:06
37         25  2017/07/08    38  17:40
38         25  2017/07/08    39  18:30
39         25  2017/07/08    40  19:10
40         25  2017/07/08    41  19:47
41         25  2017/07/09    42  13:22
42         25  2017/07/09    43  14:26
43         25  2017/07/09    44  15:08
44         25  2017/07/09    45  16:49
45         25  2017/07/09    46  17:46
46         25  2017/07/09    47  19:45
47         25  2017/07/11    48  15:15
48         25  2017/07/12    49  09:52
49         25  2017/07/12    50  12:49
...       ...         ...   ...    ...
1620       50  2018/07/20  1621  20:35
1621       50  2018/07/20  1622  21:33
1622       50  2018/07/21  1623  14:15
1623       50  2018/07/21  1624  15:32
1624       50  2018/07/22  1625  12:04
1625       50  2018/07/22  1626  13:31
1626       50  2018/07/22  1627  16:08
1627       50  2018/07/22  1628  17:17
1628       50  2018/07/22  1629  18:50
1629       25  2018/07/23  1630  19:29
1630       25  2018/07/24  1631  13:45
1631       50  2018/07/24  1632  14:13
1632       50  2018/07/26  1633  11:44
1633       50  2018/07/26  1634  12:52
1634       50  2018/07/26  1635  14:55
1635       50  2018/07/26  1636  16:35
1636       50  2018/07/27  1637  10:22
1637       50  2018/07/27  1638  11:44
1638       50  2018/07/27  1639  19:35
1639       50  2018/07/29  1640  08:28
1640       50  2018/07/29  1641  10:45
1641       50  2018/07/29  1642  12:47
1642       50  2018/07/29  1643  13:46
1643       50  2018/07/30  1644  07:25
1644       50  2018/07/30  1645  09:12
1645       50  2018/07/30  1646  11:44
1646       50  2018/07/30  1647  13:13
1647       50  2018/07/30  1648  15:32
1648       50  2018/07/30  1649  17:22
1649       50  2018/07/31  1650  13:15
1650       50  2018/08/01  1651  09:25
1651       50  2018/08/01  1652  11:05
1652       50  2018/08/01  1653  18:26
1653       50  2018/08/01  1654  19:50
1654       50  2018/08/01  1655  20:53
1655       25  2018/08/01  1656  22:04
1656       50  2018/08/02  1657  11:19
1657       50  2018/08/02  1658  12:40
1658       50  2018/08/02  1659  13:59
1659       25  2018/08/02  1660  18:28
1660       50  2018/08/02  1661  19:11
1661       50  2018/08/03  1662  15:06
1662       50  2018/08/03  1663  19:18
1663       50  2018/08/03  1664  20:13
1664       25  2018/08/03  1665  22:43
1665       50  2018/08/05  1666  12:39
1666       50  2018/08/06  1667  17:53
1667       50  2018/08/06  1668  18:43
1668       50  2018/08/06  1669  19:33
1669       50  2018/08/06  1670  20:23

[1670 rows x 4 columns]

# Work units

In [124]:
new_column_names = {'_d':'Duration', '_dt':'Date', 
                              '_id':'Id', '_p':'Project Id', '_t':'Time'}
df_work_units = json_normalize(data['workUnits'])

def format_work_units(df_original):
    df = df_original.copy()
    df['_d'] = df['_d'].apply(lambda x: print_minutes(x))
    df['_t'] = df['_t'].apply(lambda x: print_hour(x))
    df.rename(columns=new_column_names, inplace=True)
    df= df.drop("_msc", 1)
    df= df.drop("_f", 1)
    df= df.drop("_m", 1)
    return df

format_work_units(df_work_units)

     Duration        Date    Id  Project Id   Time
0          25  2017/06/30     1           1  16:42
1          25  2017/06/30     2           1  17:56
2          25  2017/06/30     3           1  18:23
3          25  2017/06/30     4           1  19:31
4          25  2017/06/30     5           1  20:07
5          25  2017/06/30     6           1  21:18
6          25  2017/07/04     7           2  11:29
7          25  2017/07/04     8           2  12:00
8          24  2017/07/04     9           2  12:49
9          25  2017/07/04    10           2  13:27
10         25  2017/07/04    11           2  21:57
11         25  2017/07/04    12           2  23:18
12         25  2017/07/05    13           2  15:18
13         25  2017/07/05    14           2  16:51
14         25  2017/07/05    15           2  18:59
15         25  2017/07/05    16           2  19:33
16         25  2017/07/05    17           2  21:54
17         25  2017/07/05    18           2  22:20
18         25  2017/07/06    19           2  09:53
19         25  2017/07/06    20           2  10:52
20         25  2017/07/06    21           2  11:43
21         25  2017/07/06    22           2  12:41
22         25  2017/07/06    23           2  13:24
23         25  2017/07/06    24           2  14:09
24         25  2017/07/06    25           2  14:47
25         25  2017/07/06    26           2  15:30
26         25  2017/07/06    27           3  17:49
27         25  2017/07/06    28           3  20:02
28         25  2017/07/06    29           3  20:35
29         25  2017/07/07    30           1  17:45
30         24  2017/07/07    31           1  18:15
31         25  2017/07/07    32           2  20:07
32         25  2017/07/07    33           2  20:43
33         25  2017/07/08    34           2  13:10
34         25  2017/07/08    35           2  13:58
35         25  2017/07/08    36           2  15:41
36         25  2017/07/08    37           2  17:06
37         25  2017/07/08    38           2  17:40
38         25  2017/07/08    39           2  18:30
39         25  2017/07/08    40           2  19:10
40         25  2017/07/08    41           2  19:47
41         25  2017/07/09    42           2  13:22
42         25  2017/07/09    43           2  14:26
43         25  2017/07/09    44           2  15:08
44         25  2017/07/09    45           2  16:49
45         25  2017/07/09    46           2  17:46
46         25  2017/07/09    47           2  19:45
47         25  2017/07/11    48           1  15:15
48         25  2017/07/12    49           1  09:52
49         25  2017/07/12    50           1  12:49
...       ...         ...   ...         ...    ...
1617       50  2018/07/20  1618          27  20:35
1618       50  2018/07/20  1619          27  21:33
1619       50  2018/07/21  1620          27  14:15
1620       49  2018/07/21  1621          27  15:32
1621       50  2018/07/22  1622          27  12:04
1622       50  2018/07/22  1623          27  13:31
1623       50  2018/07/22  1624          27  16:08
1624       50  2018/07/22  1625          27  17:17
1625       50  2018/07/22  1626          27  18:50
1626       25  2018/07/23  1627           4  19:29
1627       25  2018/07/24  1628           7  13:45
1628       50  2018/07/24  1629           7  14:13
1629       50  2018/07/26  1630          29  11:44
1630       50  2018/07/26  1631          29  12:52
1631       50  2018/07/26  1632           4  14:55
1632       50  2018/07/26  1633           4  16:35
1633       50  2018/07/27  1634           7  10:22
1634       50  2018/07/27  1635          29  11:44
1635       49  2018/07/27  1636           4  19:35
1636       50  2018/07/29  1637           4  08:28
1637       50  2018/07/29  1638           4  10:45
1638       49  2018/07/29  1639          29  12:47
1639       50  2018/07/29  1640          29  13:46
1640       50  2018/07/30  1641          27  07:25
1641       50  2018/07/30  1642          27  09:12
1642       50  2018/07/30  1643          29  11:44
1643       50  2018/07/30  1644          29  13:13
1644       50  2018/07/30  1645          29  15:32
1645       50  2018/07/30  1646          29  17:22
1646       50  2018/07/31  1647          30  13:15
1647       50  2018/08/01  1648          29  09:25
1648       50  2018/08/01  1649          29  11:05
1649       50  2018/08/01  1650          29  18:26
1650       50  2018/08/01  1651          29  19:50
1651       50  2018/08/01  1652          29  20:53
1652       25  2018/08/01  1653          31  22:04
1653       50  2018/08/02  1654          29  11:19
1654       50  2018/08/02  1655          29  12:40
1655       50  2018/08/02  1656          29  13:59
1656       25  2018/08/02  1657          31  18:28
1657       50  2018/08/02  1658          32  19:11
1658       50  2018/08/03  1659          29  15:06
1659       50  2018/08/03  1660          29  19:18
1660       50  2018/08/03  1661          29  20:13
1661       25  2018/08/03  1662          31  22:43
1662       50  2018/08/05  1663          29  12:39
1663       50  2018/08/06  1664          33  17:53
1664       50  2018/08/06  1665          33  18:43
1665       50  2018/08/06  1666          33  19:33
1666       50  2018/08/06  1667          33  20:23

[1667 rows x 5 columns]

# Projects

In [119]:
new_column_names = {'_d':'Duration', '_id': 'Id', '_l':'Last activity',
                    '_n':'Name', '_s':'State', '_p': 'Parent Project',
                   '_t': 'Creation Date', '_w': 'Pomodoro Duration'}
df_projects = json_normalize(data['projects'])

def format_projects(df_original):
    df = df_original.copy()
    df['_d'] = df['_d'].apply(lambda x: total_time(x))
    df['_l'] = df['_l'].apply(lambda x: print_datetime(x))
    df['_t'] = df['_t'].apply(lambda x: print_datetime(x))
    df.rename(columns=new_column_names, inplace=True)
    return df

format_projects(df_projects)

,Duration,Id,Last activity,Name,Parent Project,State,Creation Date,Pomodoro Duration
0,3:20,33,2018/08/06 - 21:13,Productivity Habits App,0,0,2018/08/06 - 17:46,0
1,17:30,29,2018/08/05 - 13:29,Learn React,0,0,2018/07/26 - 11:43,0
2,1:15,31,2018/08/03 - 23:08,German,0,0,2018/07/31 - 23:38,25
3,0:50,32,2018/08/02 - 20:01,Personal website,0,0,2018/08/02 - 19:11,50
4,0:50,30,2018/07/31 - 14:05,Entrepreneurship,0,0,2018/07/31 - 13:09,0
5,84:10,27,2018/07/30 - 10:02,Learn Suby,0,0,2018/06/14 - 11:36,50
6,10:0,4,2018/07/29 - 11:35,English,0,0,2017/07/31 - 15:17,0
7,356:39,7,2018/07/27 - 11:12,Tareas escuela,0,0,2017/08/18 - 22:21,0
8,8:45,13,2018/07/19 - 17:43,Русский,0,0,2018/01/18 - 19:50,0
9,4:10,28,2018/06/19 - 15:31,Capacitación técnica,0,0,2018/06/14 - 16:18,50
10,14:9,23,2018/04/28 - 18:39,Proyecto Emprendedores,0,0,2018/03/31 - 18:31,0
11,4:10,25,2018/04/17 - 14:27,Learn Angular,0,0,2018/04/06 - 06:43,0
12,2:5,24,2018/04/07 - 20:41,Decide México!,0,0,2018/04/03 - 22:09,0
13,1:40,22,2018/03/31 - 18:17,Learn Ionic,0,0,2018/03/31 - 12:34,0
14,10:24,15,2018/03/29 - 23:16,Learn Django,0,0,2018/01/24 - 22:29,0
15,7:4,20,2018/03/24 - 23:09,ABS Autobus,0,0,2018/03/24 - 23:09,0
16,2:30,18,2018/02/27 - 16:37,Algorithms,0,0,2018/02/14 - 21:44,0
17,49:9,5,2018/02/25 - 20:30,Appointment App,0,0,2017/08/04 - 19:22,0
18,1:40,19,2018/02/24 - 15:52,Learn Ruby on Rails,0,0,2018/02/23 - 12:52,0
19,5:49,17,2018/02/11 - 13:58,Unity,0,0,2018/02/10 - 10:36,0
20,2:5,16,2018/02/06 - 11:46,Comparar Super,0,0,2018/02/05 - 20:36,0
21,71:40,8,2018/02/03 - 21:30,Becario UNAM,0,0,2017/08/22 - 19:52,0
22,48:5,1,2018/01/25 - 13:42,Servicio Social,0,0,2017/06/30 - 16:41,0
23,0:50,14,2018/01/19 - 19:08,English,0,0,2018/01/19 - 15:52,0
24,31:40,2,2018/01/13 - 16:54,Learn Android,0,0,2017/06/30 - 16:41,0
25,0:25,12,2017/12/12 - 13:02,Workhouse,0,0,2017/12/12 - 12:37,0
26,0:50,11,2017/12/12 - 12:31,Self development courses,0,0,2017/12/12 - 11:29,0
27,1:40,10,2017/11/25 - 21:40,Design and Architecture software course,0,1,2017/11/25 - 19:13,0
28,1:40,9,2017/10/07 - 00:33,Hackaton,0,1,2017/10/06 - 19:46,0
29,7:30,3,2017/08/11 - 20:22,YouTube,0,0,2017/07/05 - 23:02,0
30,0:25,6,2017/08/04 - 23:07,Curso Cine,0,0,2017/08/04 - 22:42,0